version: '3.4'

volumes:
  mongo-db:

networks:
  nodeJsNet:
    external: false
    name: 'nodeJsNet'

services:
  mongodb:
    image: mongo:4.2
    restart: always
    networks:
      - nodeJsNet
    volumes:
      - mongo-db:/data/db

  calc:
    image: bpritch/crud-app:latest
    restart: always
    networks:
      - nodeJsNet
    environment:
      MONGO_URL: 'mongodb://mongodb-service:27017/crud'
    ports:
      - 8003:8003

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  