apiVersion: v1
kind: Service
metadata:
  labels: 
    app: auth
  name: auth-service
spec:
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: auth-pod
  type: ClusterIP
