# node_web_app_service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crud
  name: crud-service
spec:
  ports:
  - port: 8003
    targetPort: 8003
  selector:
    app: crud-pod
  type: ClusterIP
